export interface LocalWallpaper {
  source: number;
  genre: string;
}

// Bundled wallpapers grouped from assets/wallpapers/generes.
export const LOCAL_WALLPAPERS: LocalWallpaper[] = [
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_022.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_024.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_030.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_038.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_039.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_056.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_063.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_065.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Anime_and_Manga/anime_and_manga_070.jpg'), genre: 'Anime & Manga' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_004.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_017.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_019.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_021.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_035.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_045.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_051.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_052.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_057.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_062.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_067.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_074.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_082.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Automotive/automotive_093.jpg'), genre: 'Automotive' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_002.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_003.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_007.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_008.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_009.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_010.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_011.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_014.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_015.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_016.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_036.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_037.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_050.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_064.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_079.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_080.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Comics_and_Superheroes/comics_and_superheroes_089.jpg'), genre: 'Comics & Superheroes' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_006.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_013.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_018.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_023.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_028.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_029.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_032.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_033.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_034.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_040.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_053.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_071.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_084.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_087.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_090.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Dark_Minimalist_and_OLED/dark_minimalist_and_oled_092.jpg'), genre: 'Dark Minimalist & OLED' },
  { source: require('../assets/wallpapers/generes/Moody_Landscapes_and_Nature/moody_landscapes_and_nature_031.jpg'), genre: 'Moody Landscapes & Nature' },
  { source: require('../assets/wallpapers/generes/Moody_Landscapes_and_Nature/moody_landscapes_and_nature_066.jpg'), genre: 'Moody Landscapes & Nature' },
  { source: require('../assets/wallpapers/generes/Moody_Landscapes_and_Nature/moody_landscapes_and_nature_068.jpg'), genre: 'Moody Landscapes & Nature' },
  { source: require('../assets/wallpapers/generes/Moody_Landscapes_and_Nature/moody_landscapes_and_nature_069.jpg'), genre: 'Moody Landscapes & Nature' },
  { source: require('../assets/wallpapers/generes/Spiritual_and_Conceptual/spiritual_and_conceptual_073.jpg'), genre: 'Spiritual & Conceptual' },
  { source: require('../assets/wallpapers/generes/Spiritual_and_Conceptual/spiritual_and_conceptual_075.jpg'), genre: 'Spiritual & Conceptual' },
  { source: require('../assets/wallpapers/generes/Spiritual_and_Conceptual/spiritual_and_conceptual_077.jpg'), genre: 'Spiritual & Conceptual' },
  { source: require('../assets/wallpapers/generes/Spiritual_and_Conceptual/spiritual_and_conceptual_094.jpg'), genre: 'Spiritual & Conceptual' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_025.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_026.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_027.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_041.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_042.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_043.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_046.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_047.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_054.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_055.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_060.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_061.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_076.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_081.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_083.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Streetwear_and_Urban_Culture/streetwear_and_urban_culture_088.jpg'), genre: 'Streetwear & Urban Culture' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_001.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_005.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_012.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_020.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_044.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_048.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_049.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_058.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_059.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_072.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_078.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_085.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_086.jpg'), genre: 'Y2K & Cyber Graphics' },
  { source: require('../assets/wallpapers/generes/Y2K_and_Cyber_Graphics/y2k_and_cyber_graphics_091.jpg'), genre: 'Y2K & Cyber Graphics' },
];

export const LOCAL_WALLPAPER_SOURCES = LOCAL_WALLPAPERS.map((wallpaper) => wallpaper.source);

